In [1]:
from keras import models
from keras import layers

/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
import keras as k
print(k.__version__)

2.1.6


In [4]:
## load imdb data
from keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

17465344/17464789 [==============================] - 0s 0us/step


In [8]:
## peek at train data shape
print(train_data.shape)
print("---"*20)
print(train_data[0])
print("---"*20)
print(train_labels[:10])

(25000,)
------------------------------------------------------------
[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19,

In [9]:
## peek at test data shape
print(test_data.shape)
print("---"*20)
print(test_data[0])
print("---"*20)
print(test_labels[:10])

(25000,)
------------------------------------------------------------
[1, 591, 202, 14, 31, 6, 717, 10, 10, 2, 2, 5, 4, 360, 7, 4, 177, 5760, 394, 354, 4, 123, 9, 1035, 1035, 1035, 10, 10, 13, 92, 124, 89, 488, 7944, 100, 28, 1668, 14, 31, 23, 27, 7479, 29, 220, 468, 8, 124, 14, 286, 170, 8, 157, 46, 5, 27, 239, 16, 179, 2, 38, 32, 25, 7944, 451, 202, 14, 6, 717]
------------------------------------------------------------
[0 1 1 0 1 1 1 0 0 1]


In [11]:
## find the largest number in the first training data point
max(train_data[0])

7486

In [12]:
## decode the sequence
word_index = imdb.get_word_index()
type(word_index)

1646592/1641221 [==============================] - 0s 0us/step


dict

In [26]:
## peek at the dictionary
i = 0
for (key, value) in word_index.items():
    print(key, value)
    i = i+ 1
    if (i > 10):
        break

fawn 34701
tsukino 52006
nunnery 52007
sonja 16816
vani 63951
woods 1408
spiders 16115
hanging 2345
woody 2289
trawling 52008
hold's 52009


In [27]:
## create a reverse word index
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])


In [28]:
## peek at the reverse word index
i = 0
for (key, value) in reverse_word_index.items():
    print(key, value)
    i = i+ 1
    if (i > 10):
        break

34701 fawn
52006 tsukino
52007 nunnery
16816 sonja
63951 vani
1408 woods
16115 spiders
2345 hanging
2289 woody
52008 trawling
52009 hold's


In [44]:
## decode the first training data point
decoded_review = ' '.join([reverse_word_index.get(i-3, '?') for i in train_data[0]])

In [45]:
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [48]:
## encode the integer sequences into a binary matrix
import numpy as np

def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
    return results    

In [49]:
X_train = vectorize_sequences(train_data)
X_test = vectorize_sequences(test_data)

In [50]:
X_train[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [51]:
## vectorize labels
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [11]:
## Load mnist data
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [20]:
## peek at the train data
print(train_images.shape)
print("-"*20)
print(train_labels.shape)
print("-"*20)
print(train_labels[:10])

(60000, 28, 28)
--------------------
(60000,)
--------------------
[5 0 4 1 9 2 1 3 1 4]


In [21]:
## peek at the test data
print(test_images.shape)
print("-"*20)
print(test_labels.shape)
print("-"*20)
print(test_labels[:10])

(10000, 28, 28)
--------------------
(10000,)
--------------------
[7 2 1 0 4 1 4 9 5 9]


In [24]:
## Build network architecture
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape = (28*28,)))
network.add(layers.Dense(10, activation='softmax'))

In [25]:
## compile step
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [26]:
# prepare image data
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

In [28]:
# prepare the labels
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [29]:
# fit the model
network.fit(train_images, train_labels, epochs=10, batch_size=128)

Epoch 1/10
60000/60000 [==============================] - 8s 135us/step - loss: 0.2570 - acc: 0.9265
Epoch 2/10
60000/60000 [==============================] - 2s 27us/step - loss: 0.1048 - acc: 0.9697
Epoch 3/10
60000/60000 [==============================] - 2s 27us/step - loss: 0.0683 - acc: 0.9789
Epoch 4/10
60000/60000 [==============================] - 2s 28us/step - loss: 0.0503 - acc: 0.9848
Epoch 5/10
60000/60000 [==============================] - 2s 28us/step - loss: 0.0375 - acc: 0.9888
Epoch 6/10
60000/60000 [==============================] - 2s 28us/step - loss: 0.0280 - acc: 0.9917
Epoch 7/10
60000/60000 [==============================] - 2s 28us/step - loss: 0.0221 - acc: 0.9935
Epoch 8/10
60000/60000 [==============================] - 2s 27us/step - loss: 0.0170 - acc: 0.9949
Epoch 9/10
60000/60000 [==============================] - 2s 28us/step - loss: 0.0128 - acc: 0.9965
Epoch 10/10
60000/60000 [==============================] - 2s 29us/step - loss: 0.0095 - acc: 0.997

In [31]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test acc: ', test_acc)

10000/10000 [==============================] - 0s 45us/step
test acc:  0.9818
